csk/urls.py
from django.urls import path
from csk.views import*
app_name="csk"

urlpatterns=[
    path("dhoni/",dhoni,name='dhoni'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb

urlpatterns = [
    path("admin/", admin.site.urls),
    path("csk/",include("csk.urls")),
    path("rcb/",include("rcb.urls")),
]

rcb/urls.py
from django.urls import path
from rcb.views import*
app_name="rcb"

urlpatterns=[
    path("virat/",virat,name="virat"),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,"dhoni.html")

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,"virat.html")

templates/dhoni.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
        <centre> 
            <h1> csk page </h1>
         <h1><a href ='{% url "rcb:virat" %}'>go to virat page </a></h1>
    </body>
</html>

templates/virat.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
        <centre>
            <h1> virat page </h1>
           <h1><a href ="{% url 'csk:dhoni' %}">go back to csk page</a></h1>
    </body>
</html>